# This is a basic workflow to help you get started with Actions

name: Deploy to firebase

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the Dev branch
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Setup the code
      run: npm install
    - name: Deploy to Firebase
      uses: mohammed-atif/firebase-publish-react@v1.0
      with:
        firebase-token: ${{ secrets.FIREBASE_TOKEN }}
